import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "CaskaydiaCove Nerd Font"
size = 12
